[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["LukeBillo <n0627514@ntu.ac.uk>"]
edition = "2018"

[[bin]]
name = "main"
path = "./main/main.rs"

[dependencies]
day-1 = { path = "./day-1" }
day-2 = { path = "./day-2" }